[[redirects]]
from = "/defaultsite"
to = "/index.html"
status = 301

[[redirects]]
  from = "/*"
  to = "/deutsch"
  force = true

  [[redirects]]
  from = "/englisch.html"
  to = "/englisch"
  force = true